using System;
using System.Collections.Generic;

public static class Euro2024Teams
{
    private static readonly Dictionary<string, string> lag = new Dictionary<string, string>
    {
    // Europa
    { "Tyskland", "GER" },
    { "Skottland", "SCO" },
    { "Ungarn", "HUN" },
    { "Sveits", "SUI" },
    { "Spania", "ESP" },
    { "Italia", "ITA" },
    { "Kroatia", "CRO" },
    { "Albania", "ALB" },
    { "England", "ENG" },
    { "Danmark", "DEN" },
    { "Serbia", "SRB" },
    { "Slovenia", "SVN" },
    { "Frankrike", "FRA" },
    { "Nederland", "NED" },
    { "Polen", "POL" },
    { "Østerrike", "AUT" },
    { "Belgia", "BEL" },
    { "Portugal", "POR" },
    { "Romania", "ROU" },
    { "Slovakia", "SVK" },
    { "Tyrkia", "TUR" },
    { "Tsjekkia", "CZE" },
    { "Ukraina", "UKR" },
    { "Georgia", "GEO" },
    { "Bosnia-Hercegovina", "BIH" },
    { "Bulgaria", "BUL" },
    { "Hviterussland", "BLR" },
    { "Estland", "EST" },
    { "Finland", "FIN" },
    { "Færøyene", "FRO" },
    { "Hellas", "GRE" },
    { "Irland", "IRL" },
    { "Island", "ISL" },
    { "Kasakhstan", "KAZ" },
    { "Kosovo", "KVX" },
    { "Latvia", "LVA" },
    { "Liechtenstein", "LIE" },
    { "Litauen", "LTU" },
    { "Luxembourg", "LUX" },
    { "Malta", "MLT" },
    { "Moldova", "MDA" },
    { "Montenegro", "MNE" },
    { "Nord-Irland", "NIR" },
    { "Nord-Makedonia", "MKD" },
    { "San Marino", "SMR" },
    { "Sverige", "SWE" },
    { "Wales", "WAL" },
    { "Kypros", "CYP" },
    
    // Sør-Amerika
    { "Argentina", "ARG" },
    { "Brasil", "BRA" },
    { "Chile", "CHI" },
    { "Colombia", "COL" },
    { "Ecuador", "ECU" },
    { "Paraguay", "PAR" },
    { "Peru", "PER" },
    { "Uruguay", "URU" },
    { "Venezuela", "VEN" },
    { "Bolivia", "BOL" },

    // Nord- og Mellom-Amerika
    { "Canada", "CAN" },
    { "Costa Rica", "CRC" },
    { "Cuba", "CUB" },
    { "Den dominikanske republikk", "DOM" },
    { "El Salvador", "SLV" },
    { "Guatemala", "GUA" },
    { "Haiti", "HAI" },
    { "Honduras", "HON" },
    { "Jamaica", "JAM" },
    { "Mexico", "MEX" },
    { "Nicaragua", "NCA" },
    { "Panama", "PAN" },
    { "Puerto Rico", "PUR" },
    { "Trinidad og Tobago", "TRI" },
    { "USA", "USA" },
    { "Saint Kitts og Nevis", "SKN" },
    { "Saint Lucia", "LCA" },
    { "Grenada", "GRN" },
    { "Barbados", "BRB" },
    { "Antigua og Barbuda", "ATG" },
    { "Bahamas", "BAH" },
    { "Belize", "BLZ" },
    { "Surinam", "SUR" },
    { "Guyana", "GUY" },

    // Afrika
    { "Algerie", "ALG" },
    { "Angola", "ANG" },
    { "Benin", "BEN" },
    { "Botswana", "BOT" },
    { "Burkina Faso", "BFA" },
    { "Burundi", "BDI" },
    { "Den sentralafrikanske republikk", "CTA" },
    { "DR Kongo", "COD" },
    { "Djibouti", "DJI" },
    { "Egypt", "EGY" },
    { "Elfenbenskysten", "CIV" },
    { "Ekvatorial-Guinea", "EQG" },
    { "Eritrea", "ERI" },
    { "Eswatini", "SWZ" },
    { "Etiopia", "ETH" },
    { "Gabon", "GAB" },
    { "Gambia", "GAM" },
    { "Ghana", "GHA" },
    { "Guinea", "GUI" },
    { "Guinea-Bissau", "GNB" },
    { "Kamerun", "CMR" },
    { "Kenya", "KEN" },
    { "Komorene", "COM" },
    { "Kongo", "CGO" },
    { "Lesotho", "LES" },
    { "Liberia", "LBR" },
    { "Libya", "LBY" },
    { "Madagaskar", "MAD" },
    { "Malawi", "MWI" },
    { "Mali", "MLI" },
    { "Marokko", "MAR" },
    { "Mauritania", "MTN" },
    { "Mauritius", "MRI" },
    { "Mosambik", "MOZ" },
    { "Namibia", "NAM" },
    { "Niger", "NIG" },
    { "Nigeria", "NGA" },
    { "Rwanda", "RWA" },
    { "São Tomé og Príncipe", "STP" },
    { "Senegal", "SEN" },
    { "Seychellene", "SEY" },
    { "Sierra Leone", "SLE" },
    { "Somalia", "SOM" },
    { "Sør-Afrika", "RSA" },
    { "Sør-Sudan", "SSD" },
    { "Tanzania", "TAN" },
    { "Togo", "TOG" },
    { "Tsjad", "CHA" },
    { "Tunisia", "TUN" },
    { "Uganda", "UGA" },
    { "Zambia", "ZAM" },
    { "Zimbabwe", "ZIM" },

    // Asia
    { "Afghanistan", "AFG" },
    { "Australia", "AUS" },
    { "Aserbajdsjan", "AZE" },
    { "Bahrain", "BHR" },
    { "Bangladesh", "BAN" },
    { "Bhutan", "BHU" },
    { "Brunei", "BRU" },
    { "Filipinene", "PHI" },
    { "Forente arabiske emirater", "UAE" },
    { "Hongkong", "HKG" },
    { "India", "IND" },
    { "Indonesia", "IDN" },
    { "Iran", "IRN" },
    { "Irak", "IRQ" },
    { "Japan", "JPN" },
    { "Jemen", "YEM" },
    { "Jordan", "JOR" },
    { "Kambodsja", "CAM" },
    { "Kina", "CHN" },
    { "Kirgisistan", "KGZ" },
    { "Kuwait", "KUW" },
    { "Laos", "LAO" },
    { "Libanon", "LBN" },
    { "Malaysia", "MAS" },
    { "Maldivene", "MDV" },
    { "Mongolia", "MNG" },
    { "Myanmar", "MYA" },
    { "Nepal", "NEP" },
    { "Nord-Korea", "PRK" },
    { "Oman", "OMA" },
    { "Pakistan", "PAK" },
    { "Palestina", "PLE" },
    { "Qatar", "QAT" },
    { "Saudi-Arabia", "KSA" },
    { "Singapore", "SIN" },
    { "Sri Lanka", "SRI" },
    { "Sør-Korea", "KOR" },
    { "Syria", "SYR" },
    { "Tadsjikistan", "TJK" },
    { "Taiwan", "TPE" },
    { "Thailand", "THA" },
    { "Turkmenistan", "TKM" },
    { "Usbekistan", "UZB" },
    { "Vietnam", "VIE" },

    // Oseania
    { "Fiji", "FIJ" },
    { "New Zealand", "NZL" },
    { "Papua Ny-Guinea", "PNG" },
    { "Salomonøyene", "SOL" },
    { "Samoa", "SAM" },
    { "Amerikansk Samoa", "ASA" },
    { "Vanuatu", "VAN" },
    { "Tonga", "TGA" },
    { "Kiribati", "KIR" },
    { "Tuvalu", "TUV" },
    { "Cookøyene", "COK" },
    { "Tahiti", "TAH" }
    };

    public static string HentForkortelse(string lagNavn)
    {
        if (lag.TryGetValue(lagNavn, out string forkortelse))
        {
            return forkortelse;
        }
        else
        {
            return lagNavn;
        }
    }
}